### PR TITLE
Improve a shadow kernel for better native code-gen

### PR DESCRIPTION
**Pull request by linehill**
Improve a shadow kernel used for `__device__` variable initialization for achieving better native code in some drivers. This is known to fix the initialization code, for large `__device__` variables, compiling or running very slowly on an Intel iGPU.

### CODE REVIEW

**Review by pjaaskel — APPROVED** [review]
LGTM!

**Review by pvelesko — APPROVED** [review]
The test seems lacking pass/fail condition. Otherwise, LGTM

**Comment by pjaaskel** [comment]
I assumed the "fail condition" is the timeout of ctest: If it (still) explodes the compile time it should fail due to the watchdog.

**Comment by linehill** [comment]
Added a valgrind detected memory error.

**Pull request merged**
