### PR TITLE
Stream Semantics test

### PR DESCRIPTION
**Pull request by Sarbojit2019**
Added stream semantics test to identify streams can run independently.

### CODE REVIEW

**Comment by pvelesko** [comment]
@Sarbojit2019 missing the actual test. Also, no need to add a new test - just the hipStreamSemantics test.

**Comment by Sarbojit2019** [comment]
@pvelesko, I have updated the right test please take a look.

**Comment by pvelesko** [comment]
Unit test passing.

**Comment by Sarbojit2019** [comment]
@pvelesko, I have added few more scenarios. I have verified with the fix but majority still fails.

**Pull request closed without merging**
