### PR TITLE
Extend global scope device variable support

### PR DESCRIPTION
**Pull request by linehill**
Features:
    
* Support global scope device variables on the OpenCL backend without need of vendor extensions.
    
* HIP programs can have multiple modules with with device variables by the same name (untested). This is achieved by using the host-side shadow variable addresses, which are different per translation unit, instead of using device variable names.

### CODE REVIEW

**Comment by pvelesko** [comment]
Will run UnitTests and merge

**Comment by pvelesko** [comment]
@linehill 

Trying to build CHIP-SPV and been stuck on this for the past 10 minutes:

```bash
[ 76%] Building CXX object samples/hipSymbol/CMakeFiles/hipTestDeviceSymbol.dir/hipTestDeviceSymbol.cpp.o
cd /home/pvelesko/CHIP-SPV/build/samples/hipSymbol && /soft/compilers/clang-hipcl/13.0-experimental-v5-rel/bin/clang++  -I/home/pvelesko/CHIP-SPV/HIP/include -I/home/pvelesko/CHIP-SPV/include -Wno-duplicate-decl-specifier -Wno-tautological-constant-compare  -Wno-c++20-extensions -Wno-unused-result -Wno-delete-abstract-non-virtual-dtor -fPIE -Wno-format-extra-args -D__HIP_PLATFORM_SPIRV__= -x hip --target=x86_64-linux-gnu --hip-device-lib-path=/home/pvelesko/CHIP-SPV/build --hip-device-lib=kernellib.bc --hip-llvm-pass-path=/home/pvelesko/CHIP-SPV/build/llvm_passes -pthread -std=c++17 -MD -MT samples/hipSymbol/CMakeFiles/hipTestDeviceSymbol.dir/hipTestDeviceSymbol.cpp.o -MF CMakeFiles/hipTestDeviceSymbol.dir/hipTestDeviceSymbol.cpp.o.d -o CMakeFiles/hipTestDeviceSymbol.dir/hipTestDeviceSymbol.cpp.o -c /home/pvelesko/CHIP-SPV/samples/hipSymbol/hipTestDeviceSymbol.cpp

```

**Comment by pvelesko** [comment]
Level Zero now segfaults on streams and queue semantics samples
```
73% tests passed, 11 tests failed out of 41

Total Test time (real) =  58.51 sec

The following tests FAILED:
          1 - UnitTests_NOT_BUILT-b12d07c (Not Run) (EXPECTED)
          2 - ABMTests_NOT_BUILT-b12d07c (Not Run) (EXPECTED)
          3 - MultiProcTests_NOT_BUILT-b12d07c (Not Run) (EXPECTED)
         17 - 2d_shuffle (Failed) (EXPECTED)
         21 - stream (SEGFAULT)
         22 - unroll (Failed) (EXPECTED)
         25 - hipStreamSemantics (SEGFAULT) 
         26 - hipTestDeviceSymbol (Not Run) (Hangs during build time at 100% CPU USE for 20+ min)
         27 - hipConstantTestDeviceSymbol (Not Run) (Hangs during build time at 100% CPU USE for 20+ min)
         33 - FloydWarshall (Timeout)
         37 - hipTestDeviceLink (Not Run) (Hangs during build time at 100% CPU USE for 20+ min)
```

OpenCL also hangs on multiple samples:
```
63% tests passed, 15 tests failed out of 41

Total Test time (real) =  85.06 sec

The following tests FAILED:
          1 - UnitTests_NOT_BUILT-b12d07c (Not Run) (EXPECTED)
          2 - ABMTests_NOT_BUILT-b12d07c (Not Run) (EXPECTED)
          3 - MultiProcTests_NOT_BUILT-b12d07c (Not Run) (EXPECTED)
         17 - 2d_shuffle (Failed) (EXPECTED)
         21 - stream (Timeout)
         22 - unroll (Failed) (EXPECTED)
         25 - hipStreamSemantics (SEGFAULT)
         26 - hipTestDeviceSymbol (Not Run)(Hangs during build time at 100% CPU USE for 20+ min)
         27 - hipConstantTestDeviceSymbol (Not Run)(Hangs during build time at 100% CPU USE for 20+ min)
         33 - FloydWarshall (Timeout)
         37 - hipTestDeviceLink (Not Run) (Hangs during build time at 100% CPU USE for 20+ min)
         38 - sycl_chip_interop (SEGFAULT) (EXPECTED)
         39 - sycl_chip_interop_usm (SEGFAULT) (EXPECTED)
         40 - hip_sycl_interop (Subprocess aborted) (EXPECTED)
         41 - hip_sycl_interop_no_buffers (Subprocess aborted) (EXPECTED)
```

**Comment by pvelesko** [comment]
Fixed a couple of issues causing hangs and segfaults on samples and disabled the Symbols and Device Link samples since they failed to compile after 4+ hrs. Updated UnitTests.md

I think the compilation issues need to be resolved before merging to main.

**Comment by pvelesko** [comment]
Merged main and update UnitTests.md

**Comment by linehill** [comment]
* Rebased on latest main branch.
* Fix an infinite loop in the HipGlobalVariables LLVM pass.

**Pull request merged**
