### PR TITLE
Fixes to HIP-SYCL Interop

### PR DESCRIPTION
**Pull request by pvelesko**
Creating a separate PR with fixes to HIP-SYCL Interop

* Various compilation issues in the two samples
* One issue that needs to be addressed is SYCL calling HIP:
1. icpx compiler needs to be used to compile SYCL (at least the way that the sample is currently setup) and it is not compatible with HIP headers. Including "hip/hip_runtime.h" results in errors
2. `hipInitFromNativeHandles` Is not in the HIP API, so it must be declared in the sample itself
3. if `hipInitFromNativeHandles` returns `hipError_t` then we must include "hip/hip_runtime.h"

* A lot of formatting/linting issues.

### CODE REVIEW

**Comment by pvelesko** [comment]
Ran a quick test on Arcticus. 
```
         96 - abort (Failed)
        112 - dynamic_shared (Subprocess aborted)
        113 - hipDynamicShared (Subprocess aborted)
        114 - hipDynamicShared2 (Subprocess aborted)
        119 - hipStreamSemantics (Failed)
        128 - BitonicSort (SEGFAULT)
        133 - RecursiveGaussian (SEGFAULT)
        135 - PrintfSimple (Failed)
        136 - PrintfNOP (Failed)
        137 - PrintfDynamic (Failed)
        144 - hipNormalizedFloat (Failed)
        148 - sycl_chip_interop (SEGFAULT)
        149 - sycl_chip_interop_usm (SEGFAULT)
```

**Comment by franz** [comment]
We can remove the requirement of hip_runtime header. `hipInitFromNativeHandles` and `hipGetBackendNativeHandles` can just return an int.

**Comment by pvelesko** [comment]
> We can remove the requirement of hip_runtime header. `hipInitFromNativeHandles` and `hipGetBackendNativeHandles` can just return an int.

That's what I did in this PR. I'll mark this as ready for review when I'm done with some additional tests

**Comment by pvelesko** [comment]
`myQueue.template get_native<sycl::backend::level_zero>();` returns nullptr. That's why I was creating a new queue for SYCL-HIP interop. @Kerilk

**Pull request merged**
