### PR TITLE
Revive RDC mode - part two

### LINKED ISSUE #362: Error in spirv_hip_fp16.h with -D__HIP_NO_HALF_CONVERSIONS__=1
- [x] merge #401 
- [ ] merge #396 
- [ ] check if failing
- [x] remove `TestHipccHalfConversions` and `TestHipccHalfOperators` tests from exclusion list

The following snippet:

```
#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
```
Compiles in ROCm/hipcc but not in CHIP-SPV/hipcc with -D__HIP_NO_HALF_CONVERSIONS__=1 on the latest main (9a684ed3).

```
$ ./tandem-hipcc -c -D__HIP_NO_HALF_CONVERSIONS__=1 hip-fp16-include.hip 
vvv Running /opt/rocm/bin/hipcc -c -D__HIP_NO_HALF_CONVERSIONS__=1 hip-fp16-include.hip
^^^ DONE (exit code: 0)

vvv Running <CHIP-SPV-install>/bin/hipcc -c -D__HIP_NO_HALF_CONVERSIONS__=1 hip-fp16-include.hip
Hip Clang Compiler not found
In file included from hip-fp16-include.hip:2:
In file included from /mnt/md1/linehill/ws-chip-spv-2/install/include/hip/hip_fp16.h:41:
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/spirv_hip_fp16.h:1586:21: error: no matching conversion for C-style cast from 'float' to '__half'
                    __llvm_amdgcn_rcp_f16(static_cast<__half_raw>(x).data)};
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
^^^ DONE (exit code: 1)
```
The compilation will probably fail on the the AMDGCN intrinsic too in a later compilation phase.

### PR DESCRIPTION
**Pull request by linehill**
Enable compilation in RDC mode with hipcc.

* Propagate additional flags needed for `-fgpu-rdc` to hipcc through .hipInfo.

* Add guide for RDC mode with HIPCC.

Fixes #362 

TODOs before landing:

- [x] Merge #375.
- [x] Close CHIP-SPV/HIPCC#4.
- [x] Merge https://github.com/CHIP-SPV/chip-spv/pull/419

### CODE REVIEW

**Comment by colleeneb** [comment]
I'm interested in testing this out with the code I have--do you think it's ready for me to pull and test? I can merge in the other two PR and test if you think it's reasonable.

Thanks!

**Comment by linehill** [comment]
It’s ready for testing. You only need to pull this patch which includes the commits from the PR part one too. Be sure to update submodules too.

**Comment by colleeneb** [comment]
Thanks! This worked for my simple example. For the full application, I couldn't get it to link properly until I added "hip::deviceRDC" to the target_link_libraries link in the application's CMakeLists.txt. To do this I also modified CHIP-SPV's CMakeLists.txt as below so I could access it. I don't know if this is the intended way of using it, but I couldn't get it to work otherwise (but I am not a cmake expert so it could just be me missing something obvious.) Now that it builds, the full application is having runtime issues, but it might be unrelated. Thanks a lot for the patch!

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5e6226a3..1abbfa8f 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -535,7 +535,7 @@ add_to_config(_hipInfo_build
   HIP_OFFLOAD_RDC_SUPPLEMENT_LINK_OPTIONS
   "${HIP_RDC_SUPPLEMENT_LINK_FLAGS} --hip-path=${CMAKE_BINARY_DIR}")

-INSTALL(TARGETS CHIP host device
+INSTALL(TARGETS CHIP host device deviceRDC
   EXPORT hip-targets
   RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
   LIBRARY DESTINATION lib
```

**Comment by linehill** [comment]
Good catch. I included your fix in the #375 (which is also propagated to this PR too).

**Comment by pjaaskel** [comment]
Is this ready to be merged?

**Comment by linehill** [comment]
Not yet. The TODOs are not done yet.

**Comment by pvelesko** [comment]
merged #419 to let CI run on top of those changes @linehill

**Pull request merged**
