### PR TITLE
Add support for device side abort()

### PR DESCRIPTION
**Pull request by linehill**
This patch depends on #36 for abort() test case to succeed on the OpenCL backend.

### CODE REVIEW

**Comment by pvelesko** [comment]
@linehill Please resolve the merge conflicts.

**Comment by linehill** [comment]
Updated: resolved conflicts.

**Comment by pvelesko** [comment]
@linehill  
abort test needs to be added as a dependency. Currently, if you do `make build_tests_standalone` `abort` test doesn't get built. 

Also, abort fails on OpenCL. Is this expected?

**Comment by linehill** [comment]
Rebased and resolved conflicts.

**Comment by pvelesko** [comment]
Conflicts again after merging textures. Why does this happen?

**Comment by linehill** [comment]
Resolved conflicts.

> Conflicts again after merging textures. Why does this happen?
Happens when changes are made to same lines. Git does not try to reason how to merge those lines, it seems.

**Comment by linehill** [comment]
Resolved conflicts.

**Pull request merged**
