### PR TITLE
HIP rebase

### PR DESCRIPTION
**Pull request by pvelesko**

### CODE REVIEW

**Comment by pvelesko** [comment]
@pjaaskel  @linehill please check if this branch is building for you and tests work as expected.

**Comment by pvelesko** [comment]
One thing different here is that the Catch2 test discovery happens at the right run on ctest. So depending the `CHIP_LOGLEVEL` it might appear that the command freezes.

**Comment by pvelesko** [comment]
Actually it seems that it needs to do the test discovery every time.. this is very time consuming.

**Comment by linehill** [comment]
With a clean build and synced submodules, 59% tests passed on level-zero on my machine.

[test-summary-level0.log](https://github.com/CHIP-SPV/chip-spv/files/9722986/test-summary-level0.log)

**Comment by pvelesko** [comment]
Closing in favor of a new branch

**Pull request closed without merging**
