### PR TITLE
Implement missing __shfl* overloads

### LINKED ISSUE #364: error: call to '__shfl*' is ambiguous
```
$ cat shfl-ops.hip
#include <hip/hip_runtime.h>
__global__ void call_shfl(unsigned int *x, int y) { *x = __shfl(*x, y); }
__global__ void call_shfl(long *x, int y) { *x = __shfl(*x, y); }
__global__ void call_shfl(unsigned long *x, int y) { *x = __shfl(*x, y); }
__global__ void call_shfl(long long *x, int y) { *x = __shfl(*x, y); }
__global__ void call_shfl(unsigned long long *x, int y) { *x = __shfl(*x, y); }
__global__ void call_shfl(double *x, int y) { *x = __shfl(*x, y); }
$ ./tandem-hipcc shfl-ops.hip -c
vvv Running /opt/rocm/bin/hipcc shfl-ops.hip -c
^^^ DONE (exit code: 0)

vvv Running <CHIP-SPV-install>/bin/hipcc shfl-ops.hip -c
Hip Clang Compiler not found
shfl-ops.hip:2:58: error: call to '__shfl' is ambiguous
__global__ void call_shfl(unsigned int *x, int y) { *x = __shfl(*x, y); }
                                                         ^~~~~~
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/devicelib/sync_and_util.hh:106:23: note: candidate function
extern __device__ int __shfl(int var, int srcLane,
                      ^
/mnt/md1/linehill/ws-chip-spv-2/install/include/hip/devicelib/sync_and_util.hh:109:25: note: candidate function
extern __device__ float __shfl(float var, int srcLane,
                        ^
...
<similar error repeated for other kernels>
```
Switching the `__shfl` call to `__shfl_xor`, `__shfl_up` or `__shfl_down` yields the same error.

### PR DESCRIPTION
**Pull request by linehill**
Fixes #364.

### CODE REVIEW

**Review by pjaaskel — APPROVED** [review]
LGTM

**Comment by linehill** [comment]
FYI, the shuffle test works on my machine. Not sure why it fails on the CI.

**Comment by linehill** [comment]
Poking CI without shuffles with double arguments.

**Comment by linehill** [comment]
Lack of double precision FP support, it seems. I'll make a separate compile-time check for double shuffles then this patch is good for landing.

**Comment by pvelesko** [comment]
this is not ready yet, right?

1. all devices support doubles (env vars provided). If doubles weren't working properly we would see a lot more failures.
2. You split out the double but I don't see any logic to include/exclude. Either way, all tests pass.

**Comment by linehill** [comment]
> all devices support doubles (env vars provided). If doubles weren't working properly we would see a lot more failures.

So far dropping the shuffles with double arguments let the 'shuffle' test pass which would otherwise fail.

> You split out the double but I don't see any logic to include/exclude. Either way, all tests pass.

The issue arises when trying to execute the shuffles with double arguments. The separate test does not execute them. It just checks the compiler passes.

**Comment by pvelesko** [comment]
@pengtu does double precision emulation not work for in this use case?

**Pull request merged**
