### PR TITLE
Hip develop rebase

### PR DESCRIPTION
**Pull request by pvelesko**
* Makes #266 redundant (at least the missing ihipEvent_t)
* Rebases everything on top of latest HIP - new APIs, more tests. 
* Simplified CHIP-SPV integration into HIP-COMMON
* Adds hip-tests submodule 
* the HIP submodule has been tested to work for regular HIPAMD installation. 
* Added new HIP API placeholders
* disabled texture samples since they mirror the unit tests
* New CMake option `USE_EXTERNAL_HIP_TESTS` set to `OFF` by default. When ON, the Catch2 unit tests will be built from `hip-tests/catch` as opposed to `HIP/tests/catch`
* new tests 719->1192

### CODE REVIEW

**Comment by pvelesko** [comment]
@linehill @pjaaskel please review as I will merge this first. 

One annoying thing are the excessive casts. These are made much worse with all of our objects now inheriting from hip defined types. I am open to suggestions on how to improve that.

**Comment by linehill** [comment]
> One annoying thing are the excessive casts. These are made much worse with all of our objects now inheriting from hip defined types. I am open to suggestions on how to improve that.

One way to reduce the casts is to change the backend methods so that they accept both `hip*_t` and `CHIP*` objects and implicitly casts to `CHIP*` type. Here is an example for `findQueue()` which  eliminates a cast in `hipStreamDestroy()`:

```diff
--- a/src/CHIPBackend.cc
+++ b/src/CHIPBackend.cc
@@ -1570,7 +1570,7 @@ CHIPDevice *CHIPBackend::findDeviceMatchingProps(const hipDeviceProp_t *Props) {
   return MatchedDevice;
 }
 
-CHIPQueue *CHIPBackend::findQueue(CHIPQueue *ChipQueue) {
+CHIPQueue *CHIPBackend::findQueue(CHIPQueueArg ChipQueue) {
   auto Dev = Backend->getActiveDevice();
   LOCK(Dev->DeviceMtx); // CHIPDevice::ChipQueues_ via getQueuesNoLock()
 
diff --git a/src/CHIPBackend.hh b/src/CHIPBackend.hh
index 496f03e1..8f9a3797 100644
--- a/src/CHIPBackend.hh
+++ b/src/CHIPBackend.hh
@@ -48,6 +48,17 @@
 
 #define DEFAULT_QUEUE_PRIORITY 1
 
+class CHIPQueueArg {
+  CHIPQueue *Value = nullptr;
+
+public:
+  CHIPQueueArg(CHIPQueue *TheValue) : Value(TheValue) {}
+  CHIPQueueArg(hipStream_t TheValue)
+      : Value(reinterpret_cast<CHIPQueue *>(TheValue)) {}
+  operator CHIPQueue *() { return Value; }
+  operator const CHIPQueue *() const { return Value; }
+};
+
 static inline size_t getChannelByteSize(hipChannelFormatDesc Desc) {
   unsigned TotalNumBits = Desc.x + Desc.y + Desc.z + Desc.w;
   return ((TotalNumBits + 7u) / 8u); // Round upwards.
@@ -1837,7 +1848,7 @@ public:
    * @param q queue to find
    * @return CHIPQueue* return queue or nullptr if not found
    */
-  CHIPQueue *findQueue(CHIPQueue *ChipQueue);
+  CHIPQueue *findQueue(CHIPQueueArg ChipQueue);
 
   /**
    * @brief Add a CHIPModule to every initialized device
diff --git a/src/CHIPBindings.cc b/src/CHIPBindings.cc
index 4228d494..7d6d0f65 100644
--- a/src/CHIPBindings.cc
+++ b/src/CHIPBindings.cc
@@ -2026,8 +2026,7 @@ hipError_t hipStreamDestroy(hipStream_t Stream) {
 hipError_t hipStreamQuery(hipStream_t Stream) {
   CHIP_TRY
   CHIPInitialize();
-  auto ChipQueue = static_cast<CHIPQueue *>(Stream);
-  ChipQueue = Backend->findQueue(ChipQueue);
+  auto *ChipQueue = Backend->findQueue(Stream);
   if (ChipQueue->getCaptureStatus() != hipStreamCaptureStatusNone) {
     ChipQueue->setCaptureStatus(hipStreamCaptureStatusInvalidated);
     RETURN(hipErrorStreamCaptureInvalidated);
```

**Comment by linehill** [comment]
* CMake is giving me worrisome warnings. Could they be fixed or suppressed? The CMake output:

```
...
CMake Warning at hip-tests/catch/CMakeLists.txt:78 (message):
  HIP_VERSION_MAJOR: 5


CMake Warning at hip-tests/catch/CMakeLists.txt:79 (message):
  HIP_VERSION_MINOR: 1


CMake Warning at hip-tests/catch/CMakeLists.txt:84 (message):
  HIP_VERSION_PATCH: 0


CMake Warning at hip-tests/catch/CMakeLists.txt:85 (message):
  HIP_VERSION_PATCH_GITHASH: 0
...
```

* Unsettling CMake messages regarding empty `OFFLOAD_ARCH_STR`. Seems like something is going to break. The CMake output:

```
...
CMake Warning at hip-tests/catch/CMakeLists.txt:204 (message):
  HIP_PLATFORM is spirv, OFFLOAD_ARCH_STR is set to


-- Using offload arch string: 
-- Configuring done
...
```

* `make build_tests` fails on my machine - perhaps due to the empty `OFFLOAD_ARCH_STR` variable. Build messages:

```
...
[  1%] Built target hipconfig.bin
clang-15: error: unsupported option '--genco'
...
In file included from /mnt/md1/linehill/ws-chip-spv-2/chip-spv/hip-tests/catch/unit/device/hipDeviceGetP2PAttribute_exe.cc:20:
In file included from /mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/hip_runtime.h:123:
/mnt/md1/linehill/ws-chip-spv-2/builds/chip-spv/include/hip/hip_runtime_api.h:499:2: error: ("Must define exactly one of __HIP_PLATFORM_AMD__, __HIP_PLATFORM_NVIDIA__ or __HIP_PLATFORM_SPIRV__");
#error("Must define exactly one of __HIP_PLATFORM_AMD__, __HIP_PLATFORM_NVIDIA__ or __HIP_PLATFORM_SPIRV__");
 ^
...
```
* Lots of linting issues are being reported. Could you fix them?

**Comment by pvelesko** [comment]
> Lots of linting issues are being reported. Could you fix them?

Should be fixed now

> CMake is giving me worrisome warnings. Could they be fixed or suppressed? The CMake output:

Debug warnings. These are expected and will be removed prior to merge. 

> Unsettling CMake messages regarding empty OFFLOAD_ARCH_STR. Seems like something is going to break

Expected when building CHIP-SPV. Only used for AMD and NVIDIA. 

> One way to reduce the casts is to change the backend methods so that they accept both hip*_t and CHIP* objects and implicitly casts to CHIP* type.

Good idea. Seems like a template would work better here. Let me check.. 

> make build_tests fails on my machine

pull & submodule update. Also check the PR description - I updated it with new options.

**Comment by pvelesko** [comment]
@linehill perhaps using templates is not optimal since I will have to call a cast to downcast from HIP to CHIP classes either way. Seems like the cast itself is unavoidable? 

This simple overload seems like the simplest solution: 

```
diff --git a/src/CHIPBackend.hh b/src/CHIPBackend.hh
index 0ab60c06..62fc95c4 100644
--- a/src/CHIPBackend.hh
+++ b/src/CHIPBackend.hh
@@ -1838,6 +1838,9 @@ public:
    * @return CHIPQueue* return queue or nullptr if not found
    */
   CHIPQueue *findQueue(CHIPQueue *ChipQueue);
+  CHIPQueue *findQueue(hipStream_t ChipQueue) {
+    return findQueue(reinterpret_cast<CHIPQueue *>(ChipQueue));
+  };

   /**
    * @brief Add a CHIPModule to every initialized device
diff --git a/src/CHIPBindings.cc b/src/CHIPBindings.cc
index b4ac832f..1a1bef99 100644
--- a/src/CHIPBindings.cc
+++ b/src/CHIPBindings.cc
@@ -542,7 +542,7 @@ hipError_t hipGraphLaunch(hipGraphExec_t graphExec, hipStream_t stream) {
   CHIP_TRY
   CHIPInitialize();
   auto ChipQueue = static_cast<CHIPQueue *>(stream);
-  ChipQueue = Backend->findQueue(ChipQueue);
+  ChipQueue = Backend->findQueue(stream);
   EXEC(graphExec)->launch(ChipQueue);
   RETURN(hipSuccess);
   CHIP_CATCH
```

**Comment by linehill** [comment]
An issue with the latest update:
```
$ git submodule update --recursive --init 
fatal: remote error: upload-pack: not our ref 44ae73fceda173d7c0e867e4fb3344f9bbbe2a51
fatal: Fetched in submodule path '../HIP', but it did not contain 44ae73fceda173d7c0e867e4fb3344f9bbbe2a51. Direct fetching of that commit failed.
```

**Comment by linehill** [comment]
FYI, there is a git config (`git config push.recurseSubmodules check`) which prevents pushing if not all submodule commits have not been pushed to the upstream [[source](https://git-scm.com/book/en/v2/Git-Tools-Submodules)].

**Comment by pvelesko** [comment]
@linehill pushed

**Comment by pvelesko** [comment]
@linehill no, `make check` should be pass 100% with Level Zero at least. It looks like you ran while I was still updating. 

`Unit_hipGraphGetNodes_ParamValidation` is in your failure list but it's excluded from make check.

**Pull request merged**
