### PR TITLE
Rocprim fixes 2

### PR DESCRIPTION
**Pull request by pjaaskel**
Various fixes for issues found when porting hipCUB/rocPRIM.

### CODE REVIEW

**Comment by pvelesko** [comment]
testKernelArgs is segfaulting for all platforms. Rebasing since some changes were merged.

@pjaaskel

**Comment by linehill** [comment]
I checked out this patch and here's my results for the test case in question on my machine:
* Level0: passed.
* OpenCL/POCL/basic: passed.
* OpenCL/POCL/pthread: first run segfaulted, others passed.
* OpenCL/Intel-iGPU: passed.

**Comment by pjaaskel** [comment]
@linehill with a Debug or Release build?

**Comment by pjaaskel** [comment]
Yep, I can see that crash with cold kcache too (Debug build).

```
TestKernelArgs: /home/pjaaskel/src/llvm-project/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp:10452: void llvm::SelectionDAGISel::LowerArguments(const llvm::Function&): Assertion `NewRoot.getNode() && NewRoot.getValueType() == MVT::Other && "LowerFormalArguments didn't return a valid chain!"' failed.
```

**Comment by pvelesko** [comment]
A single test failed that's known to be flaky on other platforms. Adding `recursiveGaussian` to #396 ALL exclusion list.

**Review by pvelesko — APPROVED** [review]

**Pull request merged**
