### PR TITLE
Initial texture object support for Level0

### PR DESCRIPTION
**Pull request by linehill**
Bring initial texture object support for Level0 backend for basic texture use cases. The implementation now covers tex1D and tex2D texture functions and single channel textures (8/16/32-bit integer and single-precision floating-point).

Unit_hipCreateTextureObject_* tests  and added texture object tests are known to fail on the OpenCL backend. They will be fixed as the texture support work continues.

### CODE REVIEW

**Comment by linehill** [comment]
Rebased. Fixed clang format/tidy issues and Unit_hipCreateTextureObject_* tests cases for Level0 backend.

**Comment by linehill** [comment]
Updated:
* Added support for tex1DFetch and ted1D texture functions.
* Added more tex2D variants.
* Added support for normalized coordinates.
* Added support for normalized float texture property.
* Added a workaround for one element vectors which are not supported in SPIR-V.
* Added support for pitched texture data (pitch > width).
* Added validity checks into hipCreateTextureObject().
* Implemented hipGetTextureObjectResourceDesc().
* Fixed hipMemcpy2DToArray.
* Fixed issues in the texture lowering pass.
* Fixed filtering mode selection for linear texture resources.

**Comment by pvelesko** [comment]
@linehill conflicts

**Comment by pvelesko** [comment]
clang-tidy 

```
[Run clang-format on src/backend/Level0/CHIPBackendLevel0.cc: src/backend/Level0/CHIPBackendLevel0.cc#L1](https://github.com/CHIP-SPV/chip-spv/pull/32/files#annotation_3086222530)
File src/backend/Level0/CHIPBackendLevel0.cc (lines 1592): Code does not conform to Custom style guidelines.
```

**Comment by linehill** [comment]
Update:
* Rebased on the latest main.
* Fixed issues arising after the rebase.
* Fixed clang-tidy issues but possibly not all of them as clang-tidy errors out on some source files.
* Texture tests are known to fail on the OpenCL backend. Work has been done for it. If I have time, I’ll finish it and make separate PRs for it.

**Comment by linehill** [comment]
Fixed a compiler warning.

**Comment by pvelesko** [comment]
Merge conflicts with printf?

**Pull request merged**
