### PR TITLE
Fix OpenCL Events

### PR DESCRIPTION
**Pull request by pvelesko**

### CODE REVIEW

**Comment by pvelesko** [comment]
Iris
```
Currently Loaded Modulefiles:
 1) spack/linux-opensuse_leap15-x86_64   4) libnl/3.3.0-gcc-10.2.0-h7m7thf        7) libpciaccess/0.16-gcc-10.2.0-kluhisj  10) gcc/10.2.0-gcc-10.2.0-yudlyez              13) intel_gpu_env/single_gpu
 2) cmake/3.23.2-gcc-10.2.0-luxkr43      5) rdma-core/36.3-gcc-10.2.0-l2rnrjy     8) hwloc/master-gcc-10.2.0-fbu4tbk       11) intel_compute_runtime/release/22.22.23355
 3) gdb-11.2                             6) libfabric/1.14.0-gcc-10.2.0-hp2bsva   9) mpi/aurora_mpich/icc-sockets/49.1     12) oneapi/release/2022.10.15.001

The following tests FAILED:
	101 - Unit_hipMemcpy_MultiThread-AllAPIs (Failed)
	571 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	585 - activemask (Failed)
```

**Comment by pvelesko** [comment]
Default modules:
```
Currently Loaded Modulefiles:
 1) spack/linux-opensuse_leap15-x86_64   4) libnl/3.3.0-gcc-10.2.0-h7m7thf        7) libpciaccess/0.16-gcc-10.2.0-kluhisj                     10) gcc/10.2.0-gcc-10.2.0-yudlyez              13) intel_gpu_env/single_gpu
 2) cmake/3.23.2-gcc-10.2.0-luxkr43      5) rdma-core/36.3-gcc-10.2.0-l2rnrjy     8) hwloc/master-gcc-10.2.0-fbu4tbk                          11) intel_compute_runtime/release/22.22.23355  14) clang/clang15-spirv-omp
 3) gdb-11.2                             6) libfabric/1.14.0-gcc-10.2.0-hp2bsva   9) mpi/aurora_mpich/icc-sockets/47.2(aurora_mpich:default)  12) oneapi/eng-compiler/latest
```

Iris GPU debug
```
The following tests FAILED:
	585 - activemask (Failed)
	633 - hipTexObjCustomPitch (Timeout)
```

Iris CPU debug
```
The following tests FAILED:
	127 - Unit_hipMemset_InvalidPtrTests (Failed)
	180 - Unit_hipMallocManaged_MultiKrnlHmmAccess (Timeout)
	508 - Unit_hipMultiStream_sameDevice (SEGFAULT)
	545 - Unit_hipDeviceSynchronize_Functional (Failed)
	571 - Unit_hipStreamPerThread_MultiThread (SEGFAULT)
	572 - Unit_hipStreamPerThread_DeviceReset_1 (Subprocess aborted)
	585 - activemask (Failed)
	592 - fp16 (Subprocess aborted)
	601 - 2d_shuffle (Failed)
	606 - unroll (Failed)
	609 - hipStreamSemantics (Failed)
	613 - hipConstantTestDeviceSymbol (Subprocess aborted)
	639 - hipAddressingModes (Failed)
	662 - cuda-blackscholes (Failed)
	663 - cuda-qrng (Failed)
```

Iris GPU release
```
The following tests FAILED:
	585 - activemask (Failed)
```

Iris CPU release
```
The following tests FAILED:
	127 - Unit_hipMemset_InvalidPtrTests (Failed)
	180 - Unit_hipMallocManaged_MultiKrnlHmmAccess (Timeout)
	508 - Unit_hipMultiStream_sameDevice (SEGFAULT)
	571 - Unit_hipStreamPerThread_MultiThread (SEGFAULT)
	585 - activemask (Failed)
	592 - fp16 (Timeout)
	601 - 2d_shuffle (Failed)
	606 - unroll (Failed)
	609 - hipStreamSemantics (Failed)
	611 - hipMultiThreadAddCallback (SEGFAULT)
	639 - hipAddressingModes (Failed)
	662 - cuda-blackscholes (Failed)
	663 - cuda-qrng (Failed)
```

**Comment by pvelesko** [comment]
@pjaaskel can you check if your results match mine?

**Comment by pjaaskel** [comment]
@pvelesko did you run with or without the fixes in #162? I'll test with.

**Comment by pvelesko** [comment]
@pjaaskel I merged that branch here. Tested with and without.

**Comment by pjaaskel** [comment]
Iris Xe iGPU OpenCL (with #162 and your fix on top):

The following tests FAILED:
	571 - Unit_hipStreamPerThread_MultiThread (Subprocess aborted)
	572 - Unit_hipStreamPerThread_DeviceReset_1 (Subprocess aborted)

**Pull request closed without merging**
